 * build core. griffin.jar will be placed in dist
ant

 * build core and plugin xxx. griffin.jar and xxx-plugin.jar will be placed in dist
ant -Dplugin=xxx
e.g.
ant -Dplugin=jargon

 * make a tar file with plugin xxx
ant -Dplugin=xxx tar
